### ISSUE TITLE
Details for Outlook 2016 & 2019

### ISSUE THREAD

**Issue by jonkratz** [caniuse-email/caniuse.email#47]
I'm not seeing Outlook 2016 and Outlook 2019 listed on here. Perhaps that's because it's the same as 2013, but it would be nice if they were part of the list there. I found myself wondering if these newer email clients support the same features as Outlook.com. Could this be made clearer? Thanks!

**Comment by coliff** [comment]
good point. I'll look to get this addressed tomorrow.

**Comment by ibrahimBeladi** [comment]
@coliff Is it tomorrow yet?

**Comment by coliff** [comment]
thanks for the reminder @ibrahimBeladi - I've updated the page with client versions. Unfortunately, Outlook continues to use Word to render emails so support is near-identical :-( 

Interesting read here: https://emails.hteumeuleu.com/making-sense-of-outlooks-rendering-engine-874a50f38357
