### ISSUE TITLE
Printable table

### ISSUE THREAD

**Issue by jasonbodman** [caniuse-email/caniuse.email#48]
I wanted to print this table to use as a quick-reference at my desk. I didn't want to print the header or footer to save some ink and I thought it might be helpful to add a print media query to create a few classes to make the table more printer friendly. Glad to take this on as it should be pretty easy!

**Comment by coliff** [comment]
Great idea! Yes, would be happy for you to make a PR for this.

**Comment by coliff** [comment]
Before

![image](https://user-images.githubusercontent.com/1212885/67483696-4d62d100-f6a1-11e9-9509-cda0d1f22306.png)

and after photos :-) 

![image](https://user-images.githubusercontent.com/1212885/67484048-3375be00-f6a2-11e9-8d2c-3ed7979b5b2d.png)
