### ISSUE TITLE
'Oulook' typo on Navbar

### ISSUE THREAD

**Issue by gustavoconci** [caniuse-email/caniuse.email#52]
Navbar item "Oulook" 2007/10/13.

**Comment by coliff** [comment]
Hi there - could you please explain the issue?

**Comment by gustavoconci** [comment]
Sorry.
In the browser table of the caniuse.email site, the Outlook column is written "Oulook".

**Comment by coliff** [comment]
thanks for reporting that. Just fixed it. 👍 
https://caniuse.email/
